name: Docker CI/CD Pipeline

# Trigger the pipeline on push or pull request to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-and-push:
    # Use the latest Ubuntu runner to execute the workflow
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository code so that subsequent steps can access it
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment with the specified version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies from the 'server/requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      # Step 4: Set up Docker Buildx, which allows building multi-platform images
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub using the stored secrets for auth
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 6: Build the Docker image and push it to Docker Hub
      # - The Docker image is tagged with the GitHub commit hash so each build is unique to the branch/version
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/understanding-workflows:${{ github.sha }}
